version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:    
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"